### ISSUE TITLE
Could this be calibrated to measure irradiance?

### ISSUE THREAD

**Issue by samsabra** [leswright1977/PySpectrometer2#10]
Thank you for sharing all of your hard work, Leslie!

I'm curious if this could be calibrated to measure irradiance (mW/cm2) for specific wavelengths or if that would require a different sensor. This isn't my area of expertise, so please forgive me if this is an obviously uninformed question.

**Comment by leswright1977** [comment]
As it stands, no. The output is arbitrary units (0-255).
If you want actual irradiance data, the best way (I think) to accomplish this is with a separate photo-sensor. That way you can read irradiance directly, then scale the output from the spectrometer appropriately.

**Comment by samsabra** [comment]
Thank you, Leslie. Any recommendation on which separate photo-sensor could be added? Do you think adding a relatively inexpensive sensor like [AS7265x](https://www.sparkfun.com/products/15050) would be sufficient with it's 18 frequencies? Or would something more expensive like a [Hamamatsu C12880MA](https://groupgets.com/products/hamamatsu-c12880ma-mems-u-spectrometer) be necessary? It would be really useful if this could be used as a calibrated spectroradiometer as well.
