### ISSUE TITLE
np.int deprecated in bookworm

### ISSUE THREAD

**Issue by macckone** [leswright1977/PySpectrometer2#15]
np.int is deprecated in bookworm which uses a newer version of numpy.
we must use np.int32 or np.int64 in specFunctions.py

The following fixes it in my install:

127,128c127,128
\<               window_size = np.abs(np.int32(window_size))
\<               order = np.abs(np.int32(order))
\-\-\-
\>               window_size = np.abs(np.int(window_size))
\>               order = np.abs(np.int(order))

**Comment by leswright1977** [comment]
Now fixed as np.int32 (all it does is handle window size)
Cheers!
