### ISSUE TITLE
issue when launching the script 

### ISSUE THREAD

**Issue by zakariagith** [leswright1977/PySpectrometer2#17]
Hi all I have an issue when i launch the programm on my raspberrypi 
[0:41:12.724569968] [17237]  INFO Camera camera_manager.cpp:284 libcamera v0.1.0+118-563cd78e
Traceback (most recent call last):
  File "/home/zakar/PySpectrometer2/src/PySpectrometer2-Picam2-v1.0.py", line 55, in <module>
    picam2 = Picamera2()
             ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 242, in __init__
    camera_num = self.global_camera_info()[camera_num]['Num']
                 ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
IndexError: list index out of range
Exception ignored in: <function Picamera2.__del__ at 0x7ffeceae9f80>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 404, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 604, in close
    if self._preview:
       ^^^^^^^^^^^^^
AttributeError: 'Picamera2' object has no attribute '_preview'
can anyone help me 
thank you for the help

**Comment by nopmobiel** [comment]
Check your camera connection. I connected the cam wrong.

**Comment by zakariagith** [comment]
Thank you so much it seem to have worked , now when I launch the script I have
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Aborted
Should I get another rasbian image (I've read that it should fix the issue but which one should I get) when I try to install qt5 I have the same issue
Thank you again for your help

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by nopmobiel** [comment]
I've reinstalled raspbian entirely and it worked (with some modifications in numpy)

**Comment by zakariagith** [comment]
Thank you very it seems to work now,
