### ISSUE TITLE
Upgrading from v1. "The system appears configured for the legacy camera stack"

### ISSUE THREAD

**Issue by 68artik** [leswright1977/PySpectrometer2#2]
Hi!
I'd love to install the new v2 software version. It looks wonderful.
Could you tell me how to configure the camera for the new camera stack please?

When I run: libcamera-hello -t 0 
I get "The system appears configured for the legacy camera stack"

Thanks in advance!

**Comment by 68artik** [comment]
Sorry! I just turned off the legacy camera support in raspi-config and it works!

**Comment by leswright1977** [comment]
I was going to say, but I was AFK. Great!
