### ISSUE TITLE
Add overlays for known spectra

### ISSUE THREAD

**Issue by melange396** [leswright1977/PySpectrometer2#20]
IANASP (i am not a spectral physicist) but it might be interesting to have a way to overlay known spectra to compare with what you're currently examining.  To start with, you could incorporate information from a NIST database that you can [look up by element](https://physics.nist.gov/PhysRefData/Handbook/periodictable.htm) or via [a more elaborate search](https://physics.nist.gov/PhysRefData/ASD/lines_form.html).

**Comment by felix91gr** [comment]
Oh yes this would be amazing

**Comment by leswright1977** [comment]
Yeah, I have though about this, and possibly using the NIST data to auto-identify spectral lines. If I get time, I will have a crack at it.
