### ISSUE TITLE
Rpi4 keep restarting occasionally with PySpectrometer2

### ISSUE THREAD

**Issue by 68artik** [leswright1977/PySpectrometer2#3]
Hi!
I'm using active cooling with Rpi 4 4GB (the latest Bullseye clean install) while using PySpectrometer2. The temperatures are fine <60C, the CPU load max 50%. The computer does not look overloaded but the Rpi have tendency do restart (with and without the waterfall). My monitor resolution is 2560x1440. Any ideas what could be wrong?

BTW. I truly love the v2 software

**Comment by 68artik** [comment]
update: Same situation on 4x lower pixel count 1280x800 monitor. Rpi just restarted in 5 minutes, so it is not the window scaling. Looks like something is unstable.

**Comment by leswright1977** [comment]
That is very weird, a Python program should not be able to do that, and as you remark, although it is quite intense in terms of data processing, it is hardly hogging the CPU.
Is there any indication as to why in /var/log/syslog ?

I will attempt to replicate the behaviour.

**Comment by codeflight1** [comment]
What power supply are you using?

I know the Pis will restart if the voltage drops too much, which can happen if your power supply is not up to the task.

**Comment by leswright1977** [comment]
This is what I am thinking it will be one of the following in order:
1) PSU
2) SD Card
3) RAM/CPU Issue
4) Something may be wrong with the new picam2 Library. It is the only think in here that is accessing hardware.

**Comment by 68artik** [comment]
Thank you guys.
I'm using brand new official Raspberry Pi power supply. 
I'll wait for a reboot and then check the syslog (just launched the PySpectrometer).
It's interesting because the rebooting issue ha started since v2 introduction and that Raspberry Pi 4 is used just for the PySpectrometer.
Stay in touch!

**Comment by leswright1977** [comment]
It's a weird one for sure.
When I made the YT video, I had the thing running for about 2 hours straight (multiple takes and all that!), with screen recorder software running and the browser open.
If the issue occurs again, see what syslog says.
Cheers!

**Comment by 68artik** [comment]
I guess It was an overclocking issue!
