### ISSUE TITLE
unable to calibrate with up to 6 lasers.

### ISSUE THREAD

**Issue by DR-DAT4** [leswright1977/PySpectrometer2#9]
trying to align with up to 6 lasers as well as less produces garbage outputs when calibrating.
after IR area suddenly comes UV again?
Sometimes calibration asks for unknown and not set wavelengths?

**Comment by leswright1977** [comment]
Specifically what wavelengths are you attempting to calibrate with? Also can you please copy and paste the entire console output here as well.
